### ISSUE TITLE
Use the rollup externals config?

### ISSUE THREAD

**Issue by adjenks** [eight04/rollup-plugin-external-globals#22]
I was hoping this would not require any additional config, but I see it takes a map or a function.
Why doesn't it use the externals config built-in to rollup?
https://rollupjs.org/guide/en/#external

**Comment by adjenks** [comment]
It looks like your other plugin uses the external setting: https://github.com/eight04/rollup-plugin-iife
I think the other plugin should take care of my needs. 👍
People may still want this feature, but I suppose you can close the ticket if you're not interested.

**Comment by eight04** [comment]
What do you mean by "use the externals config"? Are you trying to map all external imports to global variables?

Note that this plugin processes the code at transform hook, which runs before bundling. When you add a module to this plugin:

1. all code that imports the module will be removed and
2. references will be rewritten to match global variable name.

Therefore rollup won't even know that you have imported that module because it will only see the global variable. It also means that you don't have to put the module to `externals` since it is not actually imported.

On the other hand, rollup's `output.globals` is used (it gives unresolved import a name) when generating the final output, after bundling. Hence you have to add the module to `externals` to prevent rollup from bundling them.

**Comment by eight04** [comment]
>  why not allow the package/variable name mapping to be defined on `output.globals`?

Three reasons:

1. My personal preference. I prefer to put the config along with the module explicitly if they work together. In this case, I don't like to put the variable name map at `output.globals` since it will only work with this plugin. If we use `output.globals`, users may remove this plugin in the future and still expect `output.globals` to work.
2. I don't want to break rollup's documentation. Since rollup said that `output.globals` only works with `iife/umd` bundles, I'll just leave them as is. Note that this plugin works with all formats since it processes the code at transform hook.
3. They have different purposes and work differently as mentioned in https://github.com/eight04/rollup-plugin-external-globals/issues/22#issuecomment-839211462

However, I don't against the idea of using `output.globals` in this plugin. Though I think the correct solution is to resolve https://github.com/rollup/rollup/issues/2374

**Comment by adjenks** [comment]
Good reasoning! Thank you.
Yes, I agree that it needs to be resolved in rollup itself eventually.
Your plugin works great though, thank you.
Perhaps code from this plugin could be be baked right into rollup, I hope they think so.
Cheers.
